<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Define robot constants -->
  <xacro:property name="base_width" value="0.185"/>
  <xacro:property name="base_length" value="0.31"/>
  <xacro:property name="base_height" value="0.04"/>

  <xacro:property name="top_width" value="0.13"/>
  <xacro:property name="top_height" value="0.07"/>
  <xacro:property name="top_length" value="0.23"/>

  <xacro:property name="wheel_radius" value="0.0420"/>
  <xacro:property name="wheel_width" value="0.025"/>
  <xacro:property name="wheel_ygap" value="0.005"/>
  <xacro:property name="wheel_zoff" value="0.035"/>
  <xacro:property name="wheel_xoff" value="0.10"/>

  <xacro:property name="caster_yoff" value="0.05"/>
  <xacro:property name="caster_xoff" value="0.2"/>

  <!-- Robot Base -->
  <link name="base_link"/>

  <!-- Robot Footprint -->
  <link name="base_footprint"/>
  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>

  <!-- Chassis-->
  <link name="chassis_base">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="cyan"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="2" w="${base_width}" d="${base_length}" h="${base_height}"/>
  </link>

  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_base"/>
    <origin xyz="${wheel_xoff} 0 0"/>
  </joint>

  <!-- Top Chassis-->
  <link name="chassis_top">
    <visual>
      <geometry>
        <box size="${top_length} ${top_width} ${top_height}"/>
      </geometry>
      <material name="cyan"/>
    </visual>
     <collision>
      <geometry>
        <box size="${top_length} ${top_width} ${top_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="0.2" w="${top_width}" d="${top_length}" h="${top_height}"/>
  </link>

  <joint name="top_joint" type="fixed">
    <parent link="chassis_base"/>
    <child link="chassis_top"/>
    <origin xyz="${top_length / 2 - base_length / 2} 0 ${base_height / 2 + top_height / 2}" rpy="0 0 0"/>
  </joint>

  <!-- Wheels -->
  <xacro:wheel prefix="drive_wheel_l" y_reflect="1"/>
  <xacro:wheel prefix="drive_wheel_r" y_reflect="-1"/>

  <!-- Caster Wheels-->
  <xacro:caster_wheel prefix="front_caster" y_reflect="1"/>
  <xacro:caster_wheel prefix="rear_caster" y_reflect="-1"/>

</robot>