<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="mount_width" value="0.06"/>
  <xacro:property name="mount_height" value="0.07"/>
  <xacro:property name="mount_length" value="0.09"/>

  <xacro:property name="laser_height" value="0.025"/>
  <xacro:property name="laser_radius" value="0.035"/>

  <!-- LIDAR Mount -->
  <link name="laser_mount">
    <visual>
      <geometry>
        <box size="${mount_length} ${mount_width} ${mount_height}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size="${mount_length} ${mount_width} ${mount_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="0.1" w="${mount_width}" d="${mount_length}" h="${mount_height}"/>
  </link>

  <joint name="laser_mount_joint" type="fixed">
    <parent link="chassis_top"/>
    <child link="laser_mount"/>
    <origin xyz="${-mount_width} 0 ${top_height / 2 + mount_height / 2}" rpy="0 0 0"/>
  </joint>

  <!-- LIDAR Sensor-->
  <link name="laser_frame">
    <visual>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_height}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.5" r="${laser_radius}" h="${laser_height}"/>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="laser_mount"/>
    <child link="laser_frame"/>
    <origin xyz="0 0 ${ mount_height / 2 + laser_height / 2}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="laser_frame">
    <material>Gazebo/Red</material>
    <sensor name="laser" type="ray">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.3</min>
          <max>12</max>
        </range>
      </ray>
      <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <argument>~/out:=scan</argument>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>laser_frame</frame_name>
      </plugin>
    </sensor>
  </gazebo>

</robot>